/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uashafidzsabri;

import java.sql.*;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hafidz
 */

public class dataParkir extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement st = null;
    /**
     * Creates new form dataParkir
     */
    
    public dataParkir() {
        initComponents();
        try {
            con = koneksi.fungsiKoneksi();
            tampilkan_masuk();
            tampilkan_keluar();
            
            
            
            
        } catch (SQLException ex) {
            System.out.println("Form Tidak Terkoneksi");
        }
        }
    
   private void tampilkan_masuk(){
       String perintah="SELECT * FROM masukparkir";
        try{
            st = con.prepareStatement(perintah);
            rs = st.executeQuery();
            DefaultTableModel tMasuk = new DefaultTableModel();
            tMasuk.addColumn("noTiket");
            tMasuk.addColumn("noPolisi");
            tMasuk.addColumn("jnsKendaraan");
            tMasuk.addColumn("tglMasuk");
            tMasuk.addColumn("jamMasuk");
  
            while (rs.next())
            {
                tMasuk.addRow(new Object []{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)                    
                });
            }
            tblMasuk.setModel(tMasuk);
            
        }
        catch(Exception e) {
            System.out.println("Data Tidak Bisa Ditampilkan "+e.getMessage());
        }
   }

   private void tampilkan_keluar() {
       String perintah="SELECT * FROM keluarparkir";
      
        try{
            st = con.prepareStatement(perintah);
            rs = st.executeQuery();
            DefaultTableModel tKeluar = new DefaultTableModel();
            tKeluar.addColumn("noTiket");
            tKeluar.addColumn("noPolisi");
            tKeluar.addColumn("jnsKendaraan");
            tKeluar.addColumn("tglKeluar");
            tKeluar.addColumn("jamKeluar");

           
            
            while (rs.next())
            {
                tKeluar.addRow(new Object []{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)

                    
                });
            }
            tblKeluar.setModel(tKeluar);

            
        }
        catch(Exception e) {
            System.out.println("Data Tidak Bisa Ditampilkan "+e.getMessage());
    }
}
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    DateTimeFormatter jam = DateTimeFormatter.ofPattern(" HH:mm:ss");
    LocalDateTime now = LocalDateTime.now();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNoPolisi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblMasuk = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMasuk = new javax.swing.JTable();
        lblHapusMasuk = new javax.swing.JLabel();
        lblMenuMasuk = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtKeluar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblKeluar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKeluar = new javax.swing.JTable();
        lblHapusKeluar = new javax.swing.JLabel();
        lblMenuKeluar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 36)); // NOI18N
        jLabel6.setText("Data Parkir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("No. Polisi");

        txtNoPolisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPolisiActionPerformed(evt);
            }
        });
        txtNoPolisi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoPolisiKeyTyped(evt);
            }
        });

        jLabel2.setText("Jenis Kendaraan");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kendaraan", "Motor", "Mobil", " " }));

        lblMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/press.png"))); // NOI18N
        lblMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMasukMousePressed(evt);
            }
        });

        tblMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Tiket", "No Polisi", "Jenis Kendaraan", "Tanggal Masuk", "Jam Masuk"
            }
        ));
        jScrollPane1.setViewportView(tblMasuk);

        lblHapusMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus.png"))); // NOI18N
        lblHapusMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHapusMasukMousePressed(evt);
            }
        });

        lblMenuMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        lblMenuMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMenuMasukMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(txtNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHapusMasuk)
                .addGap(18, 18, 18)
                .addComponent(lblMenuMasuk)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(lblMasuk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMenuMasuk)
                            .addComponent(lblHapusMasuk))
                        .addGap(40, 40, 40)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Masuk", jPanel3);

        jLabel4.setText("No Polisi");

        txtKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeluarKeyTyped(evt);
            }
        });

        jLabel5.setText("Jenis Kendaraan");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kendaraan", "Motor", "Mobil" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        lblKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save logo.png"))); // NOI18N
        lblKeluar.setText("jLabel3");
        lblKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblKeluarMousePressed(evt);
            }
        });

        tblKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Tiket", "No Polisi", "Jenis Kendaraan", "Tanggal Keluar", "Jam Keluar"
            }
        ));
        jScrollPane2.setViewportView(tblKeluar);

        lblHapusKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus.png"))); // NOI18N
        lblHapusKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHapusKeluarMousePressed(evt);
            }
        });

        lblMenuKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        lblMenuKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMenuKeluarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHapusKeluar))
                        .addGap(18, 18, 18)
                        .addComponent(lblMenuKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(lblMenuKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHapusKeluar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Keluar", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoPolisiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPolisiKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar())); 
    }//GEN-LAST:event_txtNoPolisiKeyTyped

    private void lblMasukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMasukMousePressed
        if 
            (txtNoPolisi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nomor Polisi Belum Diisi!");
        }
        
        else {
        String save = "INSERT INTO masukparkir(noPolisi,jnsKendaraan,tglMasuk,jamMasuk) VALUE (?,?,?,?)";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            st = con.prepareStatement(save);
            st.setString(1,txtNoPolisi.getText());
            st.setString(2, (String) jComboBox1.getSelectedItem());
            st.setString(3, dtf.format(now));
            st.setString(4, jam.format(now));
                        
            st.execute();
            tampilkan_masuk();

            JOptionPane.showMessageDialog(null, "Berhasil Masuk Parkirz");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_lblMasukMousePressed

    private void txtKeluarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeluarKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar())); 
    }//GEN-LAST:event_txtKeluarKeyTyped

    private void txtNoPolisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPolisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPolisiActionPerformed

    private void lblKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKeluarMousePressed
         if 
            (txtNoPolisi.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nomor Polisi Belum Diisi!");
        }
        
        else {
        String save = "INSERT INTO keluarparkir (noPolisi,jnsKendaraan,tglKeluar,jamKeluar) VALUE (?,?,?,?)";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            st = con.prepareStatement(save);
            st.setString(1,txtKeluar.getText());
            st.setString(2, (String) jComboBox2.getSelectedItem());
            st.setString(3, dtf.format(now));
            st.setString(4, jam.format(now));
                        
            st.execute();
            tampilkan_keluar();
            
            JOptionPane.showMessageDialog(null, "Berhasil Keluar Parkir!");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_lblKeluarMousePressed

    private void lblHapusKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHapusKeluarMousePressed
        int row = tblKeluar.getSelectedRow();
        String Klik = (tblKeluar.getModel().getValueAt(row, 0).toString());
        String Querydelete = "DELETE FROM keluarparkir WHERE noTiket= ? " ;
        
        try {
            st = con.prepareStatement(Querydelete);
            st.setString(1, Klik);
            st.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
            tampilkan_keluar();
                  
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_lblHapusKeluarMousePressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void lblMenuKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuKeluarMousePressed
         utama p = new utama();
         p.setVisible(true);
         dispose();
    }//GEN-LAST:event_lblMenuKeluarMousePressed

    private void lblHapusMasukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHapusMasukMousePressed
        int row = tblMasuk.getSelectedRow();
        String Klik = (tblMasuk.getModel().getValueAt(row, 0).toString());
        String Querydelete = "DELETE FROM masukparkir WHERE noTiket= ? " ;
        
        try {
            st = con.prepareStatement(Querydelete);
            st.setString(1, Klik);
            st.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
            tampilkan_masuk();
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_lblHapusMasukMousePressed

    private void lblMenuMasukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMasukMousePressed
        utama p = new utama();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblMenuMasukMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHapusKeluar;
    private javax.swing.JLabel lblHapusMasuk;
    private javax.swing.JLabel lblKeluar;
    private javax.swing.JLabel lblMasuk;
    private javax.swing.JLabel lblMenuKeluar;
    private javax.swing.JLabel lblMenuMasuk;
    private javax.swing.JTable tblKeluar;
    private javax.swing.JTable tblMasuk;
    private javax.swing.JTextField txtKeluar;
    private javax.swing.JTextField txtNoPolisi;
    // End of variables declaration//GEN-END:variables
}
